steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/ddff/app:$COMMIT_SHA'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/ddff/app:latest'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/ddff/app'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ddff
      - --image=asia-south1-docker.pkg.dev/$PROJECT_ID/ddff/app:$COMMIT_SHA
      - --region=asia-south1
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
      - --memory=512Mi
      - --cpu=1
      - --min-instances=0
      - --max-instances=10
      - --concurrency=80
      - --timeout=300
options:
  logging: CLOUD_LOGGING_ONLY
